name: ViaDisable
version: '${project.version}'
main: me.abetgt.viadisable.ViaDisable
authors: [ AbeTGT ]
description: A simple plugin that allows you to disable ViaVersion, ViaBackwards, or ViaRewind. Intended for Minehut.
depend: [ViaVersion]
softdepend:
  - ViaBackwards
  - ViaRewind
